### ISSUE TITLE
AllowPrerelease parameter cannot be found

### ISSUE THREAD

**Issue by liyuhang1997** [DarkCoderSc/PowerRemoteDesktop#12]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3094#issuecomment-536321499

![屏幕截图 2022-01-15 232615](https://user-images.githubusercontent.com/16591303/149627281-27a63ed5-d12c-4757-a0f9-33fce492b8d7.png)

**Comment by DarkCoderSc** [comment]
Hello, you are using a too old version of NuGet that doesn't support this argument. 

Follow instructions to update it and tell me ;)

**Comment by liyuhang1997** [comment]
I have been using Nuget 6.0.0.

The problem is solved after I run the following command:

```powershell
PS C:\Users\isliy> Install-Module -Name PowerShellGet -Repository PSGallery -Force
PS C:\Users\isliy> Install-Module -Name MicrosoftStaffHub -AllowPrerelease -Force
```
