### ISSUE TITLE
不好用，并非所说的简单易用

### ISSUE THREAD

**Issue by bpshou** [DarkCoderSc/PowerRemoteDesktop#24]
首先，在安装的时候，官方的安装包，并不能直接使用，会有莫名奇妙的错误。手动安装也有一些问题，我在5台电脑上测试过，只有一台电脑成功安装了。

![image](https://user-images.githubusercontent.com/22309240/154268907-2d911f77-14cc-4d5b-8996-af54efd15fe4.png)

测试运行，也会有莫名其妙的错误，这样使用起来，并非简单易用，除非专业的开发人员，否则会有一定的成本

**Comment by DarkCoderSc** [comment]
After some tests, I could not reproduce your error.

**Minimum Required PowerShell Version is 5.1**

If you are using a Windows Version prior to 10, be sure to Install PowerShell 5.1 or higher.

---

经过一些测试，我无法重现您的错误。

**所需的最低 PowerShell 版本为 5.1**

如果您使用的是 10 之前的 Windows 版本，请务必安装 PowerShell 5.1 或更高版本。
