### ISSUE TITLE
Happy to close straight away

### ISSUE THREAD

**Issue by Donovoi** [DarkCoderSc/PowerRemoteDesktop#26]
Hi! Just a quick message (sorry to raise an issue).

I'm not much of a coder so take this with a grain of salt but...

You work is some of the best Powershell I've ever seen including the open source stuff from Microsoft. 

Easy To Understand, Explicit, Easy To Follow

Just want to say thank you for your work and please keep it up!

**Comment by DarkCoderSc** [comment]
Thank you very much for your support :) Really appreciated
