### ISSUE TITLE
Remote Screen blank

### ISSUE THREAD

**Issue by satheesh360** [DarkCoderSc/PowerRemoteDesktop#30]
Hello,

Thanks for the wonderful ps script., I'm able to establish connections b/w server and viewer. But on Viewer screen is blank after the connection is established.

Is any tweak needed on my side in the script.

Advice pls.

Thank you,

Satheesh360

**Comment by DarkCoderSc** [comment]
Hello,

Can you give me a maximum of information please .

Commands used in both sides , exact PowerShell version in both sides .

Windows version in both sides etc...

Does remote machine have an active terminal session ( physical or RDP) while using PRDP ?

Thank you in advance

**Comment by satheesh360** [comment]
Hey, Thanks for the prompt response.
I have re-configured both ends. It is accessible!!

Appreciate the team for this excellent PSS.
