### ISSUE TITLE
 Exception calling "SetProcessDPIAware" with "0" argument(s): Value cannot be null.

### ISSUE THREAD

**Issue by MostHated** [DarkCoderSc/PowerRemoteDesktop#5]
Hey there,
    I am guessing that this is my own fault, as I wanted to see if a Linux viewer to connect to a Windows server, but when I attempted to connect to the server (Win 10 pro running in a VM using PowerShell 7.3.0-preview-1) from my desktop Pop_OS 21.10 using PowerShell 7.2.1 I get the following:

```powershell
❯ Invoke-RemoteDesktopViewer -ServerAddress "192.168.101.147" -ServerPort 2801 -Password "Mys3cUr3P@$$w3rD"

Power Remote Desktop - Version 1.0.3.beta.4
Jean-Pierre LESUEUR (@DarkCoderSc) ###
https://www.github.com/darkcodersc
https://www.phrozen.io

License: Apache License (Version 2.0, January 2004)
https://www.apache.org/licenses/

MethodInvocationException: Exception calling "SetProcessDPIAware" with "0" argument(s): "Value cannot be null. (Parameter 'path1')"
```
I am guessing that Linux is probably not supported? I wanted to report this, though, just in case. I checked to see if there were any parameters I might have missed for a dpi setting, but didn't see any when searching the readme for dpi, just news that hdpi was supported.

Thanks,
-MH

**Comment by DarkCoderSc** [comment]
Hello,

Unfortunately both the server and viewer can't be run outside of Windows.

I'm planning to port the viewer in different language as soon as the project is mature enough but not the server.

Regards,

JPL
