### ISSUE TITLE
Out-Null should be avoided because of its low performance.

### ISSUE THREAD

**Issue by mkht** [DarkCoderSc/PowerRemoteDesktop#7]
This project uses the `Out-Null` cmdlet in several codes, but it should be changed to `$null` assignment, because `Out-Null` has a lower performance than `$null` assignment, it is over 1000 times slower in Windows PowerShell 5.1.
In PowerShell 7.1, there is almost no difference because of the improvements, but `$null` assignment is still faster.

### Performance comparison in Windows PowerShell 5.1
```
$Buffer = New-Object byte[] 4096

# Out-Null
Measure-Command {(1..1000).ForEach({$Buffer | Out-Null})} | select TotalMilliSeconds

TotalMilliseconds
-----------------
        8050.2508


# $null assignment
Measure-Command {(1..1000).ForEach({$null = $Buffer})} | select TotalMilliSeconds

TotalMilliseconds
-----------------
           6.1887
```

**Comment by DarkCoderSc** [comment]
I didn't know that, thank you very much for this precious recommendation.
