### ISSUE TITLE
Unable to enter open bracket keys in remote session

### ISSUE THREAD

**Issue by mkht** [DarkCoderSc/PowerRemoteDesktop#9]
Keystrokes with open brackets `(` , `[` , `{` are not being sent to the remote session.
It does not occur with close brackets.

**Comment by DarkCoderSc** [comment]
I will take a close look shortly, thank you.

**Comment by DarkCoderSc** [comment]
After verification, it seems that the auto-completion of my text editor appended a `]` and `)` respectively after writing the `[` and `)`. I did not see that, nice find ;)

I will merge your changes.

Thank you
